# Generated by Django 4.1.2 on 2022-12-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orderitem_order_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
