# Generated by Django 4.1.2 on 2022-12-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_opt_price_if'),
        ('orders', '0004_alter_order_order_delete_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
