# Generated by Django 4.1.2 on 2022-12-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_price_order_quantity_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
