# Generated by Django 4.1.2 on 2022-12-16 14:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Обработка заказа', 'В обработке'), ('Сборка заказа', 'Сборка'), ('Заказ готов', 'Заказ готов'), ('Заказ завершен', 'Заказ завершен'), ('Заказ отменен', 'Заказ отменен'), ('Заказ возвращен', 'Заказ возвращен')], default='Обработка заказа', max_length=17, verbose_name='status'),
        ),
    ]
