# Generated by Django 4.1.2 on 2022-12-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_product_opt_price_if'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='opt_price_if',
            field=models.PositiveIntegerField(blank=True, default=10000, null=True, verbose_name='Количество, необходимое для оптовой цены'),
        ),
    ]
